### ISSUE TITLE
failed to parse CIDR : invalid CIDR address:

### ISSUE THREAD

**Issue by sebold-minova** [Icinga/icinga-kubernetes#102]
icinga-kubernetes and icinga-kubernetes-web is installed on Debian 11.

Starting the Systemd-Service doesn't work. Could you help me with a solution for this problem.

Output:
```
/usr/sbin/icinga-kubernetes --config /etc/icinga-kubernetes/config.yml
I0701 11:08:30.146731 3123516 database.go:285] "Connecting to database" logger="database"
E0701 11:08:30.254653 3123516 runtime.go:79] Observed a panic: failed to parse CIDR : invalid CIDR address:  (failed to parse CIDR : invalid CIDR address: )
goroutine 242 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x18ed6c0, 0xc001e4ea80})
        k8s.io/apimachinery@v0.29.2/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00047f340?})
        k8s.io/apimachinery@v0.29.2/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x18ed6c0?, 0xc001e4ea80?})
        runtime/panic.go:770 +0x132
github.com/icinga/icinga-kubernetes/pkg/schema/v1.(*Node).Obtain(0xc001e49680, {0x1d41d38, 0xc000250008})
        github.com/icinga/icinga-kubernetes/pkg/schema/v1/node.go:67 +0x11f9
github.com/icinga/icinga-kubernetes/pkg/sync/v1.(*Sync).sync.func1(0xc001d59140)
        github.com/icinga/icinga-kubernetes/pkg/sync/v1/sync.go:85 +0x4f
github.com/icinga/icinga-kubernetes/pkg/sync.(*Sink).Upsert(0x2a443d0?, {0x1d2cc10, 0xc0003ae910}, 0xc00008de18?)
        github.com/icinga/icinga-kubernetes/pkg/sync/sink.go:59 +0x38
github.com/icinga/icinga-kubernetes/pkg/sync.(*Controller).stream(0xc000169140, {0x1d2cc10, 0xc0003ae910}, 0xc0004368a0)
        github.com/icinga/icinga-kubernetes/pkg/sync/controller.go:93 +0x468
github.com/icinga/icinga-kubernetes/pkg/sync.(*Controller).Stream(0xc000169140, {0x1d2cc10, 0xc0003ae910}, 0xc0004368a0)
        github.com/icinga/icinga-kubernetes/pkg/sync/controller.go:55 +0x369
github.com/icinga/icinga-kubernetes/pkg/sync/v1.(*Sync).sync.func3()
        github.com/icinga/icinga-kubernetes/pkg/sync/v1/sync.go:98 +0x46
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 21
        golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
panic: failed to parse CIDR : invalid CIDR address:  [recovered]
        panic: failed to parse CIDR : invalid CIDR address:

goroutine 242 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00047f340?})
        k8s.io/apimachinery@v0.29.2/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x18ed6c0?, 0xc001e4ea80?})
        runtime/panic.go:770 +0x132
github.com/icinga/icinga-kubernetes/pkg/schema/v1.(*Node).Obtain(0xc001e49680, {0x1d41d38, 0xc000250008})
        github.com/icinga/icinga-kubernetes/pkg/schema/v1/node.go:67 +0x11f9
github.com/icinga/icinga-kubernetes/pkg/sync/v1.(*Sync).sync.func1(0xc001d59140)
        github.com/icinga/icinga-kubernetes/pkg/sync/v1/sync.go:85 +0x4f
github.com/icinga/icinga-kubernetes/pkg/sync.(*Sink).Upsert(0x2a443d0?, {0x1d2cc10, 0xc0003ae910}, 0xc00008de18?)
        github.com/icinga/icinga-kubernetes/pkg/sync/sink.go:59 +0x38
github.com/icinga/icinga-kubernetes/pkg/sync.(*Controller).stream(0xc000169140, {0x1d2cc10, 0xc0003ae910}, 0xc0004368a0)
        github.com/icinga/icinga-kubernetes/pkg/sync/controller.go:93 +0x468
github.com/icinga/icinga-kubernetes/pkg/sync.(*Controller).Stream(0xc000169140, {0x1d2cc10, 0xc0003ae910}, 0xc0004368a0)
        github.com/icinga/icinga-kubernetes/pkg/sync/controller.go:55 +0x369
github.com/icinga/icinga-kubernetes/pkg/sync/v1.(*Sync).sync.func3()
        github.com/icinga/icinga-kubernetes/pkg/sync/v1/sync.go:98 +0x46
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 21
        golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
```

**Comment by lippserd** [comment]
This is a bug and will be fixed from version 0.2.0. The latest images or snapshot packages already contain the fix.
