### ISSUE TITLE
[Bug]: icinga-stack-icinga-kubernetes keeps crashing with "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by Foxeronie** [Icinga/icinga-kubernetes#69]
### Affected Chart

icinga-stack

### Which version of the app contains the bug?

0.3.0

### Please describe your problem

Hi!
After installing the icinga stack via helm, the icinga-stack-icinga-kubernetes pod keeps crashing with the following log output.

```
I0411 12:55:03.767592       1 database.go:285] "Connecting to database" logger="database"
E0411 12:55:03.878359       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 743 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x181e020, 0x2a31a80})
	/go/pkg/mod/k8s.io/apimachinery@v0.29.2/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000017a40?})
	/go/pkg/mod/k8s.io/apimachinery@v0.29.2/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x181e020?, 0x2a31a80?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/icinga/icinga-kubernetes/pkg/schema/v1.(*Ingress).Obtain(0xc00048f450, {0x1d31ad0, 0xc0003df760})
	/build/pkg/schema/v1/ingress.go:102 +0x57d
github.com/icinga/icinga-kubernetes/pkg/sync/v1.(*Sync).sync.func1(0xc000d80240)
	/build/pkg/sync/v1/sync.go:85 +0x4f
github.com/icinga/icinga-kubernetes/pkg/sync.(*Sink).Upsert(0x2a34030?, {0x1d1c6f0, 0xc00041c5f0}, 0xc000d67e18?)
	/build/pkg/sync/sink.go:59 +0x38
github.com/icinga/icinga-kubernetes/pkg/sync.(*Controller).stream(0xc0000fd5c0, {0x1d1c6f0, 0xc00041c5f0}, 0xc00049ebd0)
	/build/pkg/sync/controller.go:93 +0x468
github.com/icinga/icinga-kubernetes/pkg/sync.(*Controller).Stream(0xc0000fd5c0, {0x1d1c6f0, 0xc00041c5f0}, 0xc00049ebd0)
	/build/pkg/sync/controller.go:55 +0x369
github.com/icinga/icinga-kubernetes/pkg/sync/v1.(*Sync).sync.func3()
	/build/pkg/sync/v1/sync.go:98 +0x46
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 83
	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x153bd7d]

goroutine 743 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000017a40?})
	/go/pkg/mod/k8s.io/apimachinery@v0.29.2/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x181e020?, 0x2a31a80?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/icinga/icinga-kubernetes/pkg/schema/v1.(*Ingress).Obtain(0xc00048f450, {0x1d31ad0, 0xc0003df760})
	/build/pkg/schema/v1/ingress.go:102 +0x57d
github.com/icinga/icinga-kubernetes/pkg/sync/v1.(*Sync).sync.func1(0xc000d80240)
	/build/pkg/sync/v1/sync.go:85 +0x4f
github.com/icinga/icinga-kubernetes/pkg/sync.(*Sink).Upsert(0x2a34030?, {0x1d1c6f0, 0xc00041c5f0}, 0xc000d67e18?)
	/build/pkg/sync/sink.go:59 +0x38
github.com/icinga/icinga-kubernetes/pkg/sync.(*Controller).stream(0xc0000fd5c0, {0x1d1c6f0, 0xc00041c5f0}, 0xc00049ebd0)
	/build/pkg/sync/controller.go:93 +0x468
github.com/icinga/icinga-kubernetes/pkg/sync.(*Controller).Stream(0xc0000fd5c0, {0x1d1c6f0, 0xc00041c5f0}, 0xc00049ebd0)
	/build/pkg/sync/controller.go:55 +0x369
github.com/icinga/icinga-kubernetes/pkg/sync/v1.(*Sync).sync.func3()
	/build/pkg/sync/v1/sync.go:98 +0x46
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 83
	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
```

```
    architecture: amd64
    bootID: 406da169-d74e-430b-91d2-4123fa8d3c3d
    containerRuntimeVersion: containerd://1.7.11-k3s2
    kernelVersion: 5.15.0-97-generic
    kubeProxyVersion: v1.26.13+rke2r1
    kubeletVersion: v1.26.13+rke2r1
    machineID: 0dbc36be8286482db6e70915edadf354
    operatingSystem: linux
    osImage: Ubuntu 22.04.4 LTS
    Kubernetes: v1.26.13+rke2r1
```

Best regards,
Patrick

**Comment by lippserd** [comment]
Hi @Foxeronie,

Thanks for the report. I will have a look.

Best regards,
Eric

**Comment by lippserd** [comment]
Hi @Foxeronie,

Can you please pull the image and try again. The issue should be fixed.

Best regards,
Eric

**Comment by Foxeronie** [comment]
Hi Eric,

this problem seems to be solved. Thank you! :)
But now I'm running in the next error with this pod.

```
I0412 19:32:26.050838       1 database.go:285] "Connecting to database" logger="database"
2024-04-12T21:32:26.417133870+02:00 I0412 19:32:26.417013       1 driver.go:43] "Can't connect to database. Retrying" logger="database" error="dial tcp: lookup icinga-stack-kubernetes-database: operation was canceled"
2024-04-12T21:32:26.417151387+02:00 I0412 19:32:26.417046       1 driver.go:43] "Can't connect to database. Retrying" logger="database" error="context canceled"
2024-04-12T21:32:26.417376280+02:00 I0412 19:32:26.417254       1 driver.go:43] "Can't connect to database. Retrying" logger="database" error="context canceled"
I0412 19:32:26.417356       1 driver.go:43] "Can't connect to database. Retrying" logger="database" error="dial tcp: lookup icinga-stack-kubernetes-database: operation was canceled"
2024-04-12T21:32:26.417409427+02:00 I0412 19:32:26.417372       1 driver.go:43] "Can't connect to database. Retrying" logger="database" error="dial tcp: lookup icinga-stack-kubernetes-database: operation was canceled"
2024-04-12T21:32:26.417406338+02:00 [invalid connection]
2024-04-12T21:32:26.417483281+02:00 I0412 19:32:26.417387       1 driver.go:43] "Can't connect to database. Retrying" logger="database" error="dial tcp: lookup icinga-stack-kubernetes-database: operation was canceled"
2024-04-12T21:32:26.417496599+02:00 I0412 19:32:26.417393       1 driver.go:43] "Can't connect to database. Retrying" logger="database" error="dial tcp: lookup icinga-stack-kubernetes-database: operation was canceled"
2024-04-12T21:32:26.417504349+02:00 I0412 19:32:26.417411       1 driver.go:43] "Can't connect to database. Retrying" logger="database" error="dial tcp: lookup icinga-stack-kubernetes-database: operation was canceled"
2024-04-12T21:32:26.417524360+02:00 I0412 19:32:26.417407       1 driver.go:43] "Can't connect to database. Retrying" logger="database" error="dial tcp: lookup icinga-stack-kubernetes-database: operation was canceled"
2024-04-12T21:32:26.417533293+02:00 I0412 19:32:26.417390       1 driver.go:43] "Can't connect to database. Retrying" logger="database" error="dial tcp: lookup icinga-stack-kubernetes-database: operation was canceled"
I0412 19:32:26.417633       1 driver.go:43] "Can't connect to database. Retrying" logger="database" error="context canceled"
2024-04-12T21:32:26.417790525+02:00 F0412 19:32:26.417719       1 main.go:204] can't retry: can't perform "INSERT INTO `persistent_volume_claim_ref` (`kind`, `name`, `uid`, `persistent_volume_id`) VALUES (:kind, :name, :uid, :persistent_volume_id) ON DUPLICATE KEY UPDATE `kind` = VALUES(`kind`), `name` = VALUES(`name`), `uid` = VALUES(`uid`), `persistent_volume_id` = VALUES(`persistent_volume_id`)": Error 1406 (22001): Data too long for column 'name' at row 7
failed to create fsnotify watcher: too many open files
```

Should I create a new issue for this?

Best regards,
Patrick

**Comment by lippserd** [comment]
A new issue is not necessary yet. Please run the following statement in the database:

```sql
ALTER TABLE persistent_volume_claim_ref MODIFY COLUMN name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL;
```

After that, if the daemon no longer crashes, please run the following query:

```sql
SELECT * FROM persistent_volume_claim_ref WHERE LENGTH(name) > 63;
```

And if it is ok data protection wise, please share the result. Maybe the result of the column `kind` is enough.

**Comment by Foxeronie** [comment]
I'm now getting the following error.
```
2024-04-15T09:57:52.542959591+02:00 F0415 07:57:52.542760       1 main.go:204] can't retry: can't perform "INSERT INTO `node_volume` (`mounted`, `node_id`, `device_path`) VALUES (:mounted, :node_id, :device_path) ON DUPLICATE KEY UPDATE `mounted` = VALUES(`mounted`), `node_id` = VALUES(`node_id`), `device_path` = VALUES(`device_path`)": Error 1364 (HY000): Field 'name' doesn't have a default value
```

**Comment by lippserd** [comment]
Hi @Foxeronie,

Thanks for sharing the output.

Regarding your last error: I pushed a fix. Please pull the image and try again.

Best regards,
Eric

**Comment by Foxeronie** [comment]
Hi Eric,

thanks for your work. The last output is fixed, sadly the next error appeared.
Is it outside any normal conventions to have so long names? Not that we are generally the problem with this.

```
2024-04-15T14:11:28.323929591+02:00 F0415 12:11:28.323793       1 main.go:204] can't retry: can't perform "INSERT INTO `pvc` (`storage_class`, `phase`, `name`, `volume_mode`, `actual_capacity`, `desired_access_modes`, `namespace`, `uid`, `created`, `actual_access_modes`, `minimum_capacity`, `id`, `volume_name`, `resource_version`) VALUES (:storage_class, :phase, :name, :volume_mode, :actual_capacity, :desired_access_modes, :namespace, :uid, :created, :actual_access_modes, :minimum_capacity, :id, :volume_name, :resource_version) ON DUPLICATE KEY UPDATE `storage_class` = VALUES(`storage_class`), `phase` = VALUES(`phase`), `name` = VALUES(`name`), `volume_mode` = VALUES(`volume_mode`), `actual_capacity` = VALUES(`actual_capacity`), `desired_access_modes` = VALUES(`desired_access_modes`), `namespace` = VALUES(`namespace`), `uid` = VALUES(`uid`), `created` = VALUES(`created`), `actual_access_modes` = VALUES(`actual_access_modes`), `minimum_capacity` = VALUES(`minimum_capacity`), `id` = VALUES(`id`), `volume_name` = VALUES(`volume_name`), `resource_version` = VALUES(`resource_version`)": Error 1406 (22001): Data too long for column 'name' at row 18
```

Best regards,
Patrick

**Comment by lippserd** [comment]
> Is it outside any normal conventions to have so long names? Not that we are generally the problem with this.

I thought that they are restricted, that's why the schema is limited in that regard, but obviously they're not 😆. 

Please execute the following statements to increase the available length of all volume name columns:

```sql
ALTER TABLE node_volume MODIFY COLUMN name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE pod_pvc MODIFY COLUMN volume_name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE pod_pvc MODIFY COLUMN claim_name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE pod_volume MODIFY COLUMN volume_name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE container_mount MODIFY COLUMN volume_name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE pvc MODIFY COLUMN name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE pvc MODIFY COLUMN volume_name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE persistent_volume MODIFY COLUMN name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL;
```

**Comment by Foxeronie** [comment]
> I thought that they are restricted, that's why the schema is limited in that regard, but obviously they're not 😆.

Ah, okay. :D

I ran all commands. One additional error appeared for table data, column "name".
I also modified this column with
```
ALTER TABLE data MODIFY COLUMN name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL;
```
and now the pod is runnning. :)
Thanks for the help!

**Comment by lippserd** [comment]
Fixes relevant for this issue:
* 95691e6b4b49ef9382f729a07e37409c2c775d78
* 590a802a5ee9381b549da739d4247039b849a59d
* 8e172086d759248df22ea3875b9e7e1f9f471238
* 230491b0e12283f24d1b6d2007c5899ee5cd0953
* 7b137eabf52d73611e131cd8368f99ef12097f95

**Comment by Foxeronie** [comment]
> @Foxeronie I have revised the lengths of the name columns and pushed the fixes to the main branch. It's different to what I've posted earlier. It would be really great if you could try them out. However, you would have to recreate the database, i.e. drop and create it. The schema will be imported by the daemon.

Deployment was successful! 👍 Thank you.

**Comment by lippserd** [comment]
@Foxeronie Thanks for the prompt feedback. Much appreciated.
